#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

IN_002 = ROOT / "artifacts/json/local_cell_to_reduced_universe_derivation_002.v1.json"
IN_003 = ROOT / "artifacts/json/local_cell_to_reduced_universe_boundary_audit_003.v1.json"

SEC05 = ROOT / "paper/sections/05_reduced_universe_theorem.tex"
SEC06 = ROOT / "paper/sections/06_boundary_and_next_problem.tex"

OUT_JSON = ROOT / "artifacts/json/reduced_universe_theorem_sync_004.v1.json"
OUT_NOTE = ROOT / "notes/reduced_universe_theorem_sync_004.md"


def load_json(path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print("wrote", path)


def main():
    a002 = load_json(IN_002)
    a003 = load_json(IN_003)

    if not a002.get("theorem_pass"):
        raise SystemExit("002 theorem_pass is not true")
    if not a003.get("boundary_pass"):
        raise SystemExit("003 boundary_pass is not true")

    candidates = a002["candidates"]

    table_lines = []
    for r in candidates:
        overlap = " ".join(str(x) for x in r["c_anchor_overlap"]) if r["c_anchor_overlap"] else "none"
        diag = "yes" if r["hidden_diagonal"] else "no"
        table_lines.append(
            f"{r['candidate_index']} & {r['c_state']} & {r['anchor_state']} & {diag} & \\texttt{{{overlap}}} \\\\"
        )

    sec05 = r"""\section{Reduced-universe derivation theorem}

Artifact 002 proves the central claim of this paper: the reduced 16-candidate universe is generated by taking two readouts of the Project 22 local-cell kernel.

Let
\[
    L=\{O0,O1,B0,B1\}
\]
be the Project 22 local answer-cell kernel.  The C readout is
\[
    C(L)=[O0,O1,B0,B1],
\]
and the anchor readout is
\[
    A(L)=[B0,O0,O1,B1].
\]
The reduced visible universe is
\[
    U=C(L)\times A(L),
\]
with candidate index
\[
    i=4c+a.
\]

\begin{theorem}[Local-cell-to-reduced-universe theorem]
Given the Project 22 local answer-cell kernel \(L\), the two readouts \(C(L)\) and \(A(L)\) generate exactly 16 visible candidates, indexed \(0,\ldots,15\).  The hidden identity condition
\[
    x_C=x_A
\]
selects exactly candidates
\[
    [1,6,8,15].
\]
In visible coordinates this identity selector appears as the permutation
\[
    [1,2,0,3]=(0\ 1\ 2)(3).
\]
\end{theorem}

\paragraph{Proof.}
The product of two four-state readouts has \(4\times4=16\) candidates.  Because the two readouts contain the same hidden states, the identity selector contributes one accepted candidate for each state.  The anchor positions of the C-ordered states are
\[
    O0\mapsto 1,\quad
    O1\mapsto 2,\quad
    B0\mapsto 0,\quad
    B1\mapsto 3.
\]
Therefore the visible permutation is
\[
    [1,2,0,3].
\]
Using \(i=4c+a\), the selected candidates are
\[
    4\cdot0+1=1,\quad
    4\cdot1+2=6,\quad
    4\cdot2+0=8,\quad
    4\cdot3+3=15.
\]
Thus the selected set is exactly
\[
    [1,6,8,15].
\]

\paragraph{Generated universe.}
\begin{center}
\begin{tabular}{c|c|c|c|c}
candidate & C state & anchor state & diagonal & overlap\\
\hline
""" + "\n".join(table_lines) + r"""
\end{tabular}
\end{center}

Artifact 002 verifies that the candidate count is 16, the candidate indices are \(0,\ldots,15\), the visible permutation is \([1,2,0,3]\), and the hidden diagonal is \([1,6,8,15]\).  Artifact 003 verifies that this claim is stated with the correct boundary.
"""

    sec06 = r"""\section{Boundary and next problem}

This paper derives the reduced 16-candidate universe from the Project 22 local-cell kernel.  That is a real strengthening over treating the 16 candidates as an observed support product.

The boundary audit in artifact 003 records the closed statement:

\[
    \text{Project 22 local-cell kernel}
    \longrightarrow
    \text{two readouts}
    \longrightarrow
    \text{reduced 16-candidate universe}.
\]

The same audit preserves the open boundary.  The derivation remains conditional on the Project 22 local-cell kernel.  It does not yet derive that kernel from native G60 provenance.  It also does not derive the full role-labeled shared\_B edge universe.  Therefore it does not close Gap A.

The next problem is upstream:

\[
    \text{native G60 provenance}
    \longrightarrow
    \text{local Lift \& Twist answer cell}.
\]

Only after that upstream derivation is supplied can the full Gap A closure claim be tested.
"""

    write(SEC05, sec05)
    write(SEC06, sec06)

    result = {
        "status": "reduced_universe_theorem_sync_recorded",
        "audit_id": "004",
        "inputs": {
            "002": str(IN_002),
            "003": str(IN_003),
        },
        "outputs": {
            "section_05": str(SEC05),
            "section_06": str(SEC06),
        },
        "derivation_002_theorem_pass": bool(a002.get("theorem_pass")),
        "boundary_003_pass": bool(a003.get("boundary_pass")),
        "candidate_count": a002.get("candidate_count"),
        "visible_permutation": a002.get("visible_permutation"),
        "diagonal_indices": a002.get("diagonal_indices"),
        "claim": (
            "Synced the paper to the audited Project 23 theorem: the Project 22 local-cell kernel "
            "generates the reduced 16-candidate universe as C(L) x A(L), and the hidden diagonal "
            "selects [1,6,8,15] with visible permutation [1,2,0,3]."
        ),
        "boundary": (
            "The paper preserves the boundary that this does not derive the local-cell kernel from native "
            "G60 provenance, does not derive the full role-labeled shared_B edge universe, and does not close Gap A."
        ),
    }

    write(OUT_JSON, json.dumps(result, indent=2, sort_keys=True) + "\n")

    note = """# Reduced universe theorem sync 004

Status: reduced_universe_theorem_sync_recorded

## Claim

Synced the paper to the audited Project 23 theorem. The Project 22 local-cell kernel generates the reduced 16-candidate universe as C(L) x A(L), and the hidden diagonal selects [1,6,8,15] with visible permutation [1,2,0,3].

## Boundary

The paper preserves the boundary that this does not derive the local-cell kernel from native G60 provenance, does not derive the full role-labeled shared_B edge universe, and does not close Gap A.
"""
    write(OUT_NOTE, note)

    print("status", result["status"])
    print("candidate_count", result["candidate_count"])
    print("visible_permutation", result["visible_permutation"])
    print("diagonal_indices", result["diagonal_indices"])


if __name__ == "__main__":
    main()
